name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish-tauri:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set build type
        id: build_type
        run: |
          if [[ "${{ github.ref }}" == *"rc"* ]]; then
            echo "debug=true" >> $GITHUB_OUTPUT
          else
            echo "debug=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Setup ffmpeg
        shell: pwsh
        run: ./ffmpeg_setup.ps1

      - name: Install frontend dependencies
        run: yarn install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WHISPER_BACKEND: cpu
        with:
          tagName: v__VERSION__
          releaseName: "BiliBili ShadowReplay v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ""
          includeDebug: true
